json.id event.id
json.name event.name
json.description event.description
json.user_id event.user_id
json.venue_id event.venue_id
json.start_date event.start_date
json.end_date event.end_date
json.status event.status
json.sales event.sales